### ISSUE TITLE
Not working with :global in scss file

### ISSUE THREAD

**Issue by zigotica** [antonk52/cssmodules-language-server#6]
Hi, thank you for the server. 

It is not working when CSS module is used in separate scss file, and we use `:global`

<img width="512" alt="Screenshot 2022-01-10 at 12 34 24" src="https://user-images.githubusercontent.com/178855/148759625-e0792f84-a200-4cb3-8415-bc9a7aa50f31.png">

**Comment by antonk52** [comment]
Hello and thank you for the issue! Sorry for a late reply.

I have tried to repro what I could see on a screenshot and the completion worked as expected.

![Screenshot 2022-01-18 at 11 53 56](https://user-images.githubusercontent.com/5817809/149933080-c9dd55a0-c10b-4574-bf4f-a0a20ebba753.png)

<details><summary>If the issue is about the red diagnostics from the screenshot in scss file</summary>
These are from <code>cssls</code> and not from <code>cssmodules-language-server</code>. This can be fixed with changing the selector from <code>:global(> .cell)</code> to <code>> :global(.cell)</code> as global is supposed to only wrap the classname and not the entire selector. Please see <a href="https://github.com/css-modules/css-modules#exceptions" target="_blank">css modules docs</a>.
</details>

I did notice that with this setup go-to-definition worked, but with `.cell` it lands on `:global` instead of the sell directly. It would be nice to fix this.

If you are still having an issue can you share a minimal code example that reproduces the issue?

**Comment by zigotica** [comment]
Hi ANton, thanks for your reply. You were right, this was a wrong syntax from my example. Thank you
